### ISSUE TITLE
[SM] Exception reported: Failed to connect to database 'reports'.

### ISSUE THREAD

**Issue by D3V1L9** [Mesharsky/Simple-Reports#7]
I added the "reports" to my database.cfg and isn't working

`[SM]   [1] Line 130, c:\Users\Mesha\Desktop\Github\Simple Reports\addons\sourcemod\scripting\reports.sp::OnConfigsExecuted`

My database.cfg

"reports"
    {
        "driver"           	"mysql"
        "host"              "localhost"
        "database"      "reports"
        "user"              "myuser"
        "pass"              "mypass"
    }

**Comment by m4csim** [comment]
Try to specify the port or the real localhost address of your database

**Comment by Mesharsky** [comment]
Plugin works fine. You need working credentials for mysql database for plugin to work.
Either server hosting can provide with free database or you can create it locally / buy it somewhere.
