### ISSUE TITLE
Feature suggestion

### ISSUE THREAD

**Issue by Rexi489** [Mesharsky/Simple-Reports#8]
Hello,  nice plugin, thank you, I want to make a few suggestions for you to improve. i have made a suggestion in the forum before

https://forums.alliedmods.net/showpost.php?p=2786604&postcount=5

- If there is an admin in the game, don't show admin in menu
-  Block people from reporting ( to prevent unnecessary reporting )

**Comment by Mesharsky** [comment]
Hello,

Thanks for the feedback, i will work on it soon and add extra settings into configuration file.
It's added to my TODO list so hopefully i make it soon enough.
I will close this thread once it's completed and tested.

Regards
